### ISSUE TITLE
500 failed to fetch user profile

### ISSUE THREAD

**Issue by mauricionr** [jaredhanson/passport-yammer#6]
500 failed to fetch user profile (status: 401 data: )
at C:\Users\mauricionunes\Source\Repos\yammerbotwebapp\yammerbotwebapp\node_modules\passport-yammer\lib\passport-yammer\strategy.js:104:28
at passBackControl (C:\Users\mauricionunes\Source\Repos\yammerbotwebapp\yammerbotwebapp\node_modules\passport-yammer\node_modules\passport-oauth\node_modules\oauth\lib\oauth2.js:123:9)
at IncomingMessage. (C:\Users\mauricionunes\Source\Repos\yammerbotwebapp\yammerbotwebapp\node_modules\passport-yammer\node_modules\passport-oauth\node_modules\oauth\lib\oauth2.js:142:7)
at IncomingMessage.emit (events.js:129:20)
at _stream_readable.js:908:16
at process._tickCallback (node.js:355:11)

**Comment by rinku9900** [comment]
@mauricionr @jaredhanson are you guys able to figure out the above error? I am also getting the same error. Please help resolving it.

**Comment by jfstephe** [comment]
For others finding this issue (and me in the future), I believe, pending confirmation, that this module is out of date and doesn't work. There are PRs and issues that look to fix it but again waiting for status updates.
